name: Create and Push Nuget Package

on:
  push:
    branches: [ "main", "release/*" ]
    paths-ignore:
    - '.github/workflows/**'

  workflow_dispatch:

# Add permissions here for the GITHUB_TOKEN
permissions:
  contents: read # Required to checkout code
  packages: write # Required to publish packages (and implicitly read for your own packages)


jobs:
  job_1:
    name: Create Nuget Package
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v2
          
      - name: Download NuGet.exe
        run: curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe 
  
      - name: Clear NuGet Caches
        run: dotnet nuget locals all --clear
  
      - name: Restore dependencies
        #env:
            # Explicitly pass the GITHUB_TOKEN as an environment variable
            # This can sometimes resolve subtle issues with how NuGet picks it up
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore Wrapper/Wrapper.sln

      - name: Build
        run: |
            msbuild /p:Configuration=Release Wrapper/Wrapper.sln
            ls

      - name: Create Package
        shell: bash
        run: |
          cd Wrapper
          REF="${GITHUB_REF}"
          if [[ "$REF" == "refs/heads/main" ]]; then
             # This will likely result in a package version like 1.0.1-dev.123
             # The reason your 1.0.1.0 is becoming 1.0.1 is due to NuGet's adherence to Semantic Versioning (SemVer) 
             # and its internal normalization rules.
            nuget.exe pack Wrapper.nuspec -version "1.0.1.0-dev.${GITHUB_RUN_NUMBER}"
          elif [[ "$REF" == refs/heads/release/* ]]; then
            # Recommend changing this to 1.0.1 for standard SemVer
            nuget.exe pack Wrapper.nuspec -version "1.0.1.0"
          fi          
          ls
  
      - name: Push Package
        run: |
          cd Wrapper
          pwd
          ls
          dotnet nuget push Wrapper.*.nupkg --source "https://nuget.pkg.github.com/zawmyohtet2009/index.json" -k ${{ secrets.GITHUB_TOKEN }}
