name: Create and Push Nuget Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "release/*" ]
  workflow_dispatch:

# Add permissions here for the GITHUB_TOKEN
permissions:
  contents: read # Required to checkout code
  packages: read # Required to publish packages (and implicitly read for your own packages)


jobs:
  job_1:
    name: Create Nuget Package
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Or whatever .NET version your projects use
          
      - name: Download NuGet.exe
        run: curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe 

      - name: Show nuget.config content
        run: cat Wrapper\nuget.config
        shell: bash  
  
      - name: Restore dependencies
        run: dotnet restore Wrapper\Wrapper.sln --configfile=Wrapper\nuget.config --verbosity diag

      - name: Build
        run: |
            msbuild /p:Configuration=Release Wrapper\Wrapper.sln --configfile=Wrapper\nuget.config
            ls

      - name: Create Package
        shell: bash
        run: |
          cd Wrapper
          REF="${GITHUB_REF}"
          if [[ "$REF" == "refs/heads/main" ]]; then
            nuget.exe pack Wrapper.nuspec -version "1.0.1.0-dev.${GITHUB_RUN_NUMBER}"
          elif [[ "$REF" == refs/heads/release/* ]]; then
            nuget.exe pack Wrapper.nuspec -version "1.0.1.0"
          fi          
          ls
  
      - name: Push Package
        run: |
          cd Wrapper
          pwd
          ls
          dotnet nuget push Wrapper.*.nupkg --source "https://nuget.pkg.github.com/zawmyohtet2009/index.json" -k ${{ secrets.GITHUB_TOKEN }}
